name: AWS assume-role
on: 
  push:
    branches: [ master ]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: deploy-role-session
          aws-region: ap-northeast-1

      - run: aws sts get-caller-identity

